In [64]:
import numpy as np
import pandas as pd

In [65]:
df = pd.read_csv("test.csv")
df.head()

,id,battery_power,blue,clock_speed,dual_sim,int_memory,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,three_g,touch_screen,wifi
0,1,1043,1,1.8,1,5,193,3,16,226,1412,3476,12,7,0,1,0
1,2,841,1,0.5,1,61,191,5,12,746,857,3895,6,0,1,0,0
2,3,1807,1,2.8,0,27,186,3,4,1270,1366,2396,17,10,0,1,1
3,4,1546,0,0.5,1,25,96,8,20,295,1752,3893,10,0,1,1,0
4,5,1434,0,1.4,0,49,108,6,18,749,810,1773,15,8,1,0,1

In [66]:
#Set beneficial and Non beneficial criteria to all
beneficial = df[['battery_power','blue','clock_speed','dual_sim','int_memory','n_cores','pc','px_height','px_width'
                 ,'ram','sc_h','three_g','touch_screen','wifi']]
print(beneficial.head())

   battery_power  blue  clock_speed  dual_sim  int_memory  n_cores  pc  \
0           1043     1          1.8         1           5        3  16
1            841     1          0.5         1          61        5  12
2           1807     1          2.8         0          27        3   4
3           1546     0          0.5         1          25        8  20
4           1434     0          1.4         0          49        6  18

   px_height  px_width   ram  sc_h  three_g  touch_screen  wifi
0        226      1412  3476    12        0             1     0
1        746       857  3895     6        1             0     0
2       1270      1366  2396    17        0             1     1
3        295      1752  3893    10        1             1     0
4        749       810  1773    15        1             0     1

In [67]:
Non_beneficial = df[['mobile_wt']]
print(Non_beneficial.head())

   mobile_wt
0        193
1        191
2        186
3         96
4        108

In [68]:
for i in beneficial:
    column = beneficial[i]
    max=column.max()
#     print(max)
    beneficial[i] = (beneficial[i] / max)

beneficial

c:\users\abhay\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,battery_power,blue,clock_speed,dual_sim,int_memory,n_cores,pc,px_height,px_width,ram,sc_h,three_g,touch_screen,wifi
0,0.521761,1.0,0.600000,1.0,0.078125,0.375,0.80,0.118511,0.706707,0.871396,0.631579,0.0,1.0,0.0
1,0.420710,1.0,0.166667,1.0,0.953125,0.625,0.60,0.391190,0.428929,0.976435,0.315789,1.0,0.0,0.0
2,0.903952,1.0,0.933333,0.0,0.421875,0.375,0.20,0.665967,0.683684,0.600652,0.894737,0.0,1.0,1.0
3,0.773387,0.0,0.166667,1.0,0.390625,1.000,1.00,0.154693,0.876877,0.975934,0.526316,1.0,1.0,0.0
4,0.717359,0.0,0.466667,0.0,0.765625,0.750,0.90,0.392764,0.405405,0.444472,0.789474,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.850425,1.0,0.633333,0.0,0.843750,0.875,0.85,0.337703,0.456957,0.531712,0.736842,1.0,1.0,0.0
996,0.304652,0.0,0.600000,1.0,0.203125,0.500,0.10,0.604090,0.816817,0.484583,0.421053,0.0,1.0,1.0
997,0.592796,0.0,0.466667,0.0,0.125000,0.125,0.60,0.250131,0.412913,0.306593,0.263158,1.0,0.0,0.0
998,0.766883,1.0,0.166667,1.0,0.781250,0.250,0.60,0.019927,0.416416,0.628980,0.789474,0.0,1.0,0.0
999,0.635318,1.0,0.166667,0.0,0.546875,0.750,0.95,0.239643,0.304304,0.708950,0.473684,1.0,0.0,1.0

In [69]:
for i in Non_beneficial:
    column = Non_beneficial[i]
    min=column.min()
#     print(max)
    Non_beneficial[i] = (min / Non_beneficial[i])

Non_beneficial

c:\users\abhay\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

     mobile_wt
0     0.414508
1     0.418848
2     0.430108
3     0.833333
4     0.740741
..         ...
995   0.470588
996   0.430108
997   1.000000
998   0.467836
999   0.571429

[1000 rows x 1 columns]

In [73]:
frames = [beneficial, Non_beneficial]
df2 = pd.concat([beneficial, Non_beneficial], axis=1)
df2

,battery_power,blue,clock_speed,dual_sim,int_memory,n_cores,pc,px_height,px_width,ram,sc_h,three_g,touch_screen,wifi,mobile_wt
0,0.521761,1.0,0.600000,1.0,0.078125,0.375,0.80,0.118511,0.706707,0.871396,0.631579,0.0,1.0,0.0,0.414508
1,0.420710,1.0,0.166667,1.0,0.953125,0.625,0.60,0.391190,0.428929,0.976435,0.315789,1.0,0.0,0.0,0.418848
2,0.903952,1.0,0.933333,0.0,0.421875,0.375,0.20,0.665967,0.683684,0.600652,0.894737,0.0,1.0,1.0,0.430108
3,0.773387,0.0,0.166667,1.0,0.390625,1.000,1.00,0.154693,0.876877,0.975934,0.526316,1.0,1.0,0.0,0.833333
4,0.717359,0.0,0.466667,0.0,0.765625,0.750,0.90,0.392764,0.405405,0.444472,0.789474,1.0,0.0,1.0,0.740741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.850425,1.0,0.633333,0.0,0.843750,0.875,0.85,0.337703,0.456957,0.531712,0.736842,1.0,1.0,0.0,0.470588
996,0.304652,0.0,0.600000,1.0,0.203125,0.500,0.10,0.604090,0.816817,0.484583,0.421053,0.0,1.0,1.0,0.430108
997,0.592796,0.0,0.466667,0.0,0.125000,0.125,0.60,0.250131,0.412913,0.306593,0.263158,1.0,0.0,0.0,1.000000
998,0.766883,1.0,0.166667,1.0,0.781250,0.250,0.60,0.019927,0.416416,0.628980,0.789474,0.0,1.0,0.0,0.467836
999,0.635318,1.0,0.166667,0.0,0.546875,0.750,0.95,0.239643,0.304304,0.708950,0.473684,1.0,0.0,1.0,0.571429

In [74]:
# Set weight for each column
weight=1/(len(df2. columns))
for i in df2:
    column = df2[i]
    df2[i] = (df2[i] * weight)
df2

,battery_power,blue,clock_speed,dual_sim,int_memory,n_cores,pc,px_height,px_width,ram,sc_h,three_g,touch_screen,wifi,mobile_wt
0,0.034784,0.066667,0.040000,0.066667,0.005208,0.025000,0.053333,0.007901,0.047114,0.058093,0.042105,0.000000,0.066667,0.000000,0.027634
1,0.028047,0.066667,0.011111,0.066667,0.063542,0.041667,0.040000,0.026079,0.028595,0.065096,0.021053,0.066667,0.000000,0.000000,0.027923
2,0.060263,0.066667,0.062222,0.000000,0.028125,0.025000,0.013333,0.044398,0.045579,0.040043,0.059649,0.000000,0.066667,0.066667,0.028674
3,0.051559,0.000000,0.011111,0.066667,0.026042,0.066667,0.066667,0.010313,0.058458,0.065062,0.035088,0.066667,0.066667,0.000000,0.055556
4,0.047824,0.000000,0.031111,0.000000,0.051042,0.050000,0.060000,0.026184,0.027027,0.029631,0.052632,0.066667,0.000000,0.066667,0.049383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.056695,0.066667,0.042222,0.000000,0.056250,0.058333,0.056667,0.022514,0.030464,0.035447,0.049123,0.066667,0.066667,0.000000,0.031373
996,0.020310,0.000000,0.040000,0.066667,0.013542,0.033333,0.006667,0.040273,0.054454,0.032306,0.028070,0.000000,0.066667,0.066667,0.028674
997,0.039520,0.000000,0.031111,0.000000,0.008333,0.008333,0.040000,0.016675,0.027528,0.020440,0.017544,0.066667,0.000000,0.000000,0.066667
998,0.051126,0.066667,0.011111,0.066667,0.052083,0.016667,0.040000,0.001328,0.027761,0.041932,0.052632,0.000000,0.066667,0.000000,0.031189
999,0.042355,0.066667,0.011111,0.000000,0.036458,0.050000,0.063333,0.015976,0.020287,0.047263,0.031579,0.066667,0.000000,0.066667,0.038095

In [80]:
df2["Score"] = df2.sum(axis=1)
df2

,battery_power,blue,clock_speed,dual_sim,int_memory,n_cores,pc,px_height,px_width,ram,sc_h,three_g,touch_screen,wifi,mobile_wt,Score
0,0.034784,0.066667,0.040000,0.066667,0.005208,0.025000,0.053333,0.007901,0.047114,0.058093,0.042105,0.000000,0.066667,0.000000,0.027634,0.541172
1,0.028047,0.066667,0.011111,0.066667,0.063542,0.041667,0.040000,0.026079,0.028595,0.065096,0.021053,0.066667,0.000000,0.000000,0.027923,0.553113
2,0.060263,0.066667,0.062222,0.000000,0.028125,0.025000,0.013333,0.044398,0.045579,0.040043,0.059649,0.000000,0.066667,0.066667,0.028674,0.607287
3,0.051559,0.000000,0.011111,0.066667,0.026042,0.066667,0.066667,0.010313,0.058458,0.065062,0.035088,0.066667,0.066667,0.000000,0.055556,0.646522
4,0.047824,0.000000,0.031111,0.000000,0.051042,0.050000,0.060000,0.026184,0.027027,0.029631,0.052632,0.066667,0.000000,0.066667,0.049383,0.558167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.056695,0.066667,0.042222,0.000000,0.056250,0.058333,0.056667,0.022514,0.030464,0.035447,0.049123,0.066667,0.066667,0.000000,0.031373,0.639087
996,0.020310,0.000000,0.040000,0.066667,0.013542,0.033333,0.006667,0.040273,0.054454,0.032306,0.028070,0.000000,0.066667,0.066667,0.028674,0.497628
997,0.039520,0.000000,0.031111,0.000000,0.008333,0.008333,0.040000,0.016675,0.027528,0.020440,0.017544,0.066667,0.000000,0.000000,0.066667,0.342817
998,0.051126,0.066667,0.011111,0.066667,0.052083,0.016667,0.040000,0.001328,0.027761,0.041932,0.052632,0.000000,0.066667,0.000000,0.031189,0.525829
999,0.042355,0.066667,0.011111,0.000000,0.036458,0.050000,0.063333,0.015976,0.020287,0.047263,0.031579,0.066667,0.000000,0.066667,0.038095,0.556458